import { sequenceParity } from "../helpers.ts";

sequenceParity(
  "long stateful script matches SQLite after each step",
  [],
  [
    { sql: "CREATE TABLE items(id INTEGER PRIMARY KEY, name TEXT, qty INTEGER DEFAULT 0)" },
    { sql: "INSERT INTO items(name, qty) VALUES ('a', 1),('b', 2)" },
    { sql: "CREATE INDEX items_name ON items(name)" },
    { sql: "INSERT INTO items(name, qty) VALUES ('c', 3)" },
    { sql: "UPDATE items SET qty = qty + 1 WHERE name = 'a'" },
    { sql: "BEGIN" },
    { sql: "UPDATE items SET qty = 99 WHERE name = 'b'" },
    { sql: "SAVEPOINT sp1" },
    { sql: "DELETE FROM items WHERE name = 'c'" },
    { sql: "ROLLBACK TO sp1" },
    { sql: "INSERT INTO items(name, qty) VALUES ('d', 4)" },
    { sql: "RELEASE sp1" },
    { sql: "COMMIT" },
    { sql: "ALTER TABLE items ADD COLUMN note TEXT DEFAULT 'n'" },
    { sql: "CREATE TABLE stock(item_id INTEGER REFERENCES items(id), n INT)" },
    { sql: "INSERT INTO stock VALUES (1, 10),(2, 20)" },
    { sql: "BEGIN" },
    { sql: "UPDATE stock SET n = n + 1 WHERE item_id = 1" },
    { sql: "SAVEPOINT sp2" },
    { sql: "DELETE FROM stock WHERE item_id = 2" },
    { sql: "ROLLBACK TO sp2" },
    { sql: "COMMIT" },
    { sql: "SELECT id, name, qty, note FROM items ORDER BY id", query: true },
    { sql: "SELECT item_id, n FROM stock ORDER BY item_id", query: true },
    { sql: "DROP INDEX items_name" },
    { sql: "SELECT name, qty FROM items ORDER BY id", query: true },
  ],
  { compareFinalState: true },
);

sequenceParity(
  "mixed DDL DML txn PRAGMA script matches oracle",
  [],
  [
    { sql: "PRAGMA foreign_keys = ON" },
    { sql: "CREATE TABLE parent(id INTEGER PRIMARY KEY, name TEXT)" },
    { sql: "CREATE TABLE child(id INTEGER PRIMARY KEY, parent_id INTEGER REFERENCES parent(id), note TEXT)" },
    { sql: "INSERT INTO parent(name) VALUES ('p1'),('p2')" },
    { sql: "INSERT INTO child(parent_id, note) VALUES (1,'c1'),(2,'c2')" },
    { sql: "BEGIN" },
    { sql: "SAVEPOINT sp_a" },
    { sql: "UPDATE child SET note = 'edited' WHERE id = 1" },
    { sql: "CREATE INDEX child_note ON child(note)" },
    { sql: "ROLLBACK TO sp_a" },
    { sql: "INSERT INTO child(parent_id, note) VALUES (1,'c3')" },
    { sql: "RELEASE sp_a" },
    { sql: "COMMIT" },
    { sql: "ALTER TABLE child ADD COLUMN tag TEXT DEFAULT 't'" },
    { sql: "CREATE VIEW child_v AS SELECT id, note, tag FROM child" },
    { sql: "SELECT id, parent_id, note, tag FROM child ORDER BY id", query: true },
    { sql: "SELECT id, note FROM child_v ORDER BY id", query: true },
    { sql: "PRAGMA foreign_keys", query: true },
  ],
  { compareFinalState: true },
);
