import { runCatalog } from "./run.ts";

runCatalog("FUN", [
  { id: "FUN-length-01", kind: "parity", sql: "SELECT length('héllo')" },
  { id: "FUN-length-02", kind: "parity", sql: "SELECT length(X'C3A9')" },
  { id: "FUN-length-03", kind: "parity", sql: "SELECT length(12345)" },
  { id: "FUN-octet-01", kind: "parity", sql: "SELECT octet_length('héllo'), octet_length(X'C3A9')" },
  { id: "FUN-substr-01", kind: "parity", sql: "SELECT substr('abcde', -2)" },
  { id: "FUN-substr-02", kind: "parity", sql: "SELECT substr('abcde', 1, 2)" },
  { id: "FUN-substr-03", kind: "parity", sql: "SELECT substr('abcde', 2, -1)" },
  { id: "FUN-substr-04", kind: "parity", sql: "SELECT hex(substr(X'01020304', 2, 2))" },
  { id: "FUN-substr-05", kind: "parity", sql: "SELECT substring('abcde', 2, 2)" },
  { id: "FUN-instr-01", kind: "parity", sql: "SELECT instr('abc','b'), instr(X'010203', X'02')" },
  { id: "FUN-replace-01", kind: "parity", sql: "SELECT replace('aaa','','x'), replace('aba','a','x')" },
  { id: "FUN-upper-01", kind: "parity", sql: "SELECT upper('AbÄ')" },
  { id: "FUN-lower-01", kind: "parity", sql: "SELECT lower('AbÄ')" },
  { id: "FUN-trim-01", kind: "parity", sql: "SELECT trim('  x  '), ltrim('xxa','x'), rtrim('axx','x')" },
  { id: "FUN-hex-01", kind: "parity", sql: "SELECT hex('A'), hex(X'0A')" },
  { id: "FUN-unhex-01", kind: "parity", sql: "SELECT hex(unhex('0A 0B', ' '))" },
  { id: "FUN-unhex-02", kind: "parity", sql: "SELECT unhex('GG')" },
  { id: "FUN-quote-01", kind: "parity", sql: "SELECT quote('a''b'), quote(X'00'), quote(1.5), quote(NULL)" },
  { id: "FUN-char-01", kind: "parity", sql: "SELECT char(65,66)" },
  { id: "FUN-unicode-01", kind: "parity", sql: "SELECT unicode('A'), unicode('é')" },
  { id: "FUN-soundex-01", kind: "parity", sql: "SELECT soundex('Robert')" },
  {
    id: "FUN-printf-01",
    kind: "parity",
    sql: "SELECT printf('%d', 3)",
  },
  { id: "FUN-printf-02", kind: "parity", sql: "SELECT printf('%-10s|%010d|%.3f', 'a', 7, 1.2)" },
  { id: "FUN-printf-03", kind: "parity", sql: "SELECT format('%s', 'a')" },
  { id: "FUN-abs-01", kind: "parity", sql: "SELECT abs(-3), abs(-1.5)" },
  { id: "FUN-abs-02", kind: "parity", sql: "SELECT abs(-3)" },
  { id: "FUN-round-01", kind: "parity", sql: "SELECT round(1.5), round(1.25, 1)" },
  { id: "FUN-round-02", kind: "parity", sql: "SELECT round(123.456, -1)" },
  { id: "FUN-sign-01", kind: "parity", sql: "SELECT sign(-2), sign(0), sign(3.5)" },
  { id: "FUN-minmax-01", kind: "parity", sql: "SELECT min(1, NULL, 2), max(1, NULL, 2)" },
  { id: "FUN-minmax-02", kind: "parity", sql: "SELECT min(1,2)" },
  { id: "FUN-random-01", kind: "parity", sql: "SELECT typeof(random())" },
  {
    id: "FUN-randomblob-01",
    kind: "parity",
    sql: "SELECT length(randomblob(4))",
  },
  { id: "FUN-zeroblob-01", kind: "parity", sql: "SELECT length(zeroblob(4))" },
  { id: "FUN-hint-01", kind: "parity", sql: "SELECT likelihood(5, 0.5), likely(5), unlikely(5)" },
  { id: "FUN-math-01", kind: "parity", sql: "SELECT sqrt(4), acos(1)" },
  { id: "FUN-math-02", kind: "parity", sql: "SELECT typeof(ceil(1.0)), typeof(floor(1.2)), trunc(1.9)" },
  { id: "FUN-math-03", kind: "parity", sql: "SELECT log(100), log10(100), log2(8), log(2, 8), pow(2,3), power(2,3)" },
  { id: "FUN-math-04", kind: "parity", sql: "SELECT mod(7,3), mod(-7,3), mod(7,-3)" },
  { id: "FUN-math-05", kind: "parity", sql: "SELECT pi() BETWEEN 3 AND 4, degrees(pi()), radians(180)" },
  { id: "FUN-typeof-01", kind: "parity", sql: "SELECT typeof(1), typeof(1.0), typeof('a'), typeof(X''), typeof(NULL)" },
  { id: "FUN-version-01", kind: "parity", sql: "SELECT typeof(sqlite_version())" },
  { id: "FUN-source-01", kind: "parity", sql: "SELECT typeof(sqlite_source_id())" },
  {
    id: "FUN-lastrow-01",
    kind: "sequence",
    setup: ["CREATE TABLE t(a INTEGER PRIMARY KEY)"],
    steps: [{ sql: "INSERT INTO t VALUES (NULL)" }, { sql: "SELECT last_insert_rowid()", query: true }],
  },
  {
    id: "FUN-changes-01",
    kind: "sequence",
    setup: ["CREATE TABLE t(a INTEGER)"],
    steps: [{ sql: "INSERT INTO t VALUES (1),(2)" }, { sql: "SELECT changes(), total_changes()", query: true }],
  },
  { id: "FUN-like-fn-01", kind: "parity", sql: "SELECT like('a%', 'abc'), 'abc' LIKE 'a%'" },
  { id: "FUN-glob-fn-01", kind: "parity", sql: "SELECT glob('a*', 'abc'), 'abc' GLOB 'a*'" },
  { id: "FUN-coalesce-01", kind: "error", sql: "SELECT coalesce(1)", query: true },
  { id: "FUN-null-01", kind: "parity", sql: "SELECT length(NULL), abs(NULL), upper(NULL)" },
  { id: "FUN-arity-01", kind: "error", sql: "SELECT abs(1,2)", query: true },
]);
