import {
  type CatalogSection,
  catalogTestFile,
  type Scenario,
  type ScenarioKind,
  type SectionCode,
} from "./scenario-types.ts";

type Row = [suffix: string, title: string, kind?: ScenarioKind, notes?: string, extraEvidence?: string[]];

function divergenceIdFor(id: string): string | undefined {
  if (id.includes("negzero")) return "negzero-canonicalization";
  if (
    id.startsWith("DAT-now") ||
    id === "DAT-mod-08" ||
    id.startsWith("DET-seed") ||
    id === "DET-os-01" ||
    id === "DET-eval-01" ||
    id.startsWith("DET-rb") ||
    id === "TXN-rb-03" ||
    id.startsWith("SNP-now") ||
    id === "SNP-rng-01"
  ) {
    return "deterministic-random-now";
  }
  if (id === "TYP-nan-04" || id === "TYP-nan-05") return "nan-infinity-bind";
  if (id === "JSN-sub-03") return "json-api-unwrap";
  if (id === "SEL-dup-01" || id === "DML-ret-02" || id === "API-ret-03") return "js-api-surface";
  if (id === "CTE-mat-01") return "materialized-hint-ignored";
  if (
    id === "TRG-snap-01" ||
    id.startsWith("SNP-omit") ||
    id === "ATT-snap-01" ||
    id === "FTS-snap-01"
  ) {
    return "snapshot-exclusions";
  }
  if (id === "PRG-fn-01" || id === "PRG-comp-01") return "compile-options-function-list";
  if (id === "PRG-beh-05") return "user-version-snapshot";
  if (id === "PRG-beh-02" || id === "PRG-beh-03" || id === "PRG-beh-07") return "pragma-setter-noop";
  if (id === "FTS-series-01") return "generate-series-extension";
  if (id === "FTS-chg-01") return "fts-shadow-counters";
  if (id === "DAT-mod-localtime" || id === "datetime-localtime-utc") return "datetime-localtime-utc";
  if (id === "ATT-att-01") return "attach-empty-schema";
  if (id === "TOK-07") return "double-quote-string-fallback";
  if (id === "UNI-surr-01") return "lone-surrogate-bind";
  return undefined;
}

function section(code: SectionCode, title: string, promoted: boolean, items: Row[]): CatalogSection {
  return {
    code,
    title,
    promoted,
    scenarios: items.map(([suffix, rowTitle, kind = "differential", notes, extra]) => {
      const id = `${code}-${suffix}`;
      const extraEvidence = extra ?? [];
      const scenario: Scenario = {
        id,
        title: rowTitle,
        kind,
        evidence: [catalogTestFile(code), ...extraEvidence],
      };
      if (notes !== undefined) scenario.notes = notes;
      if (kind === "documented_divergence") scenario.divergenceId = divergenceIdFor(id);
      return scenario;
    }),
  };
}

const D: ScenarioKind = "documented_divergence";
const F: ScenarioKind = "fuzz";
const P: ScenarioKind = "property";
const E: ScenarioKind = "ecosystem";

const HEAD: CatalogSection[] = [
  section("TOK", "Tokenizer & lexical layer", true, [
    ["01", "Keywords are case-insensitive"],
    ["02", "Double-quoted identifiers"],
    ["03", "Backtick-quoted identifiers"],
    ["04", "Bracket-quoted identifiers"],
    ["05", "Embedded quote escaping in identifiers"],
    ["06", "Quoted keywords as identifiers"],
    ["07", "Double-quoted unknown identifier falls back to string literal", D, "mem rejects unknown double-quoted ids"],
    ["08", "String literal '' escape"],
    ["09", "String literals with embedded newlines"],
    ["10", "Empty string literal"],
    ["11", "NUL byte inside TEXT literal"],
    ["12", "Empty blob literal x''"],
    ["13", "Blob literal X'ABCD'"],
    ["14", "Odd-length hex blob literal errors"],
    ["15", "Lowercase hex blob literal"],
    ["16", "Integer literal 1"],
    ["17", "Unary minus on numeric literal"],
    ["18", "Decimal 1.5"],
    ["19", "Leading-dot decimal .5"],
    ["20", "Trailing-dot decimal 5."],
    ["21", "Scientific 1e10"],
    ["22", "Scientific 1E-10"],
    ["23", "Hex integer 0x1A"],
    ["24", "Hex integer overflow beyond 64 bits errors"],
    ["25", "Leading zeros on integers"],
    ["26", "INT64_MAX literal"],
    ["27", "INT64_MAX+1 becomes REAL"],
    ["28", "Huge exponent 9e999 is Inf REAL"],
    ["29", "Line comments -- to EOL"],
    ["30", "Block comments /* */"],
    ["31", "Unterminated block comment at EOF is accepted"],
    ["32", "Comment between tokens"],
    ["33", "Comment-only script"],
    ["34", "Unicode identifiers"],
    ["35", "Unicode string content"],
    ["36", "Identifiers with $ and _"],
    ["37", "Trailing semicolons"],
    ["38", "Repeated semicolons"],
    ["39", "Leading semicolons"],
    ["40", "Empty statement in exec vs prepare/query"],
    ["41", "Tab whitespace"],
    ["42", "CRLF whitespace"],
    ["43", "Form-feed whitespace"],
    ["44", "Vertical-tab whitespace"],
  ]),
  section("PAR", "Parser & statement coverage", true, [
    ["select-01", "SELECT parses"],
    ["values-01", "VALUES statement parses"],
    ["insert-01", "INSERT parses"],
    ["update-01", "UPDATE parses"],
    ["delete-01", "DELETE parses"],
    ["create-table-01", "CREATE TABLE parses"],
    ["create-index-01", "CREATE INDEX parses"],
    ["create-view-01", "CREATE VIEW parses"],
    ["create-trigger-01", "CREATE TRIGGER parses"],
    ["create-vtable-01", "CREATE VIRTUAL TABLE parses"],
    ["drop-table-01", "DROP TABLE parses"],
    ["drop-index-01", "DROP INDEX parses"],
    ["drop-view-01", "DROP VIEW parses"],
    ["drop-trigger-01", "DROP TRIGGER parses"],
    ["alter-01", "ALTER TABLE parses"],
    ["begin-01", "BEGIN/COMMIT/END/ROLLBACK parse"],
    ["savepoint-01", "SAVEPOINT/RELEASE parse"],
    ["pragma-01", "PRAGMA parses"],
    ["attach-01", "ATTACH/DETACH parse"],
    ["analyze-01", "ANALYZE parses"],
    ["reindex-01", "REINDEX parses"],
    ["vacuum-01", "VACUUM parses"],
    ["explain-01", "EXPLAIN parses"],
    ["with-01", "WITH parses"],
    ["prec-01", "OR binds looser than AND"],
    ["prec-02", "AND binds looser than NOT"],
    ["prec-03", "NOT binds looser than comparison"],
    ["collate-01", "COLLATE binds tighter than unary operators"],
    ["like-escape-01", "ESCAPE on LIKE"],
    ["not-like-01", "NOT LIKE"],
    ["not-in-01", "NOT IN"],
    ["not-between-01", "NOT BETWEEN"],
    ["not-glob-01", "NOT GLOB"],
    ["depth-01", "Deeply nested parentheses"],
    ["syntax-01", "Syntax error category at prepare time"],
    ["multi-01", "Multi-statement prepare/query is misuse"],
    ["multi-02", "Multi-statement exec runs all"],
    ["reserved-01", "Reserved-word misuse SELECT FROM t"],
  ]),
  section("TYP", "Storage classes, affinity, coercion", true, [
    ["aff-01", "INT* declared type → INTEGER affinity"],
    ["aff-02", "CHAR/CLOB/TEXT declared type → TEXT affinity"],
    ["aff-03", "BLOB or empty declared type → BLOB affinity"],
    ["aff-04", "REAL/FLOA/DOUB declared type → REAL affinity"],
    ["aff-05", "Other declared types → NUMERIC affinity"],
    ["aff-06", "FLOATING POINT is INTEGER via INT in POINT"],
    ["aff-07", "STRING declared type → NUMERIC"],
    ["ins-01", "'123' into INTEGER stores INTEGER"],
    ["ins-02", "'123abc' into INTEGER stays TEXT"],
    ["ins-03", "'1.0' into INTEGER stores INTEGER 1"],
    ["ins-04", "BLOB never converted by affinity"],
    ["typeof-01", "typeof after insert paths"],
    ["typeof-02", "Integer-valued REAL typeof is real"],
    ["cast-01", "CAST TEXT→INTEGER prefix parse 12abc", undefined, undefined, ["tests/contract/matrices/m2-cast.test.ts"]],
    ["cast-02", "CAST TEXT→INTEGER leading spaces"],
    ["cast-03", "CAST 'abc' AS INTEGER is 0"],
    ["cast-04", "CAST REAL→INTEGER truncates toward zero"],
    ["cast-05", "CAST INTEGER→TEXT formatting"],
    ["cast-06", "CAST anything→BLOB"],
    ["cast-07", "CAST of NULL"],
    ["cast-08", "CAST overflow clamps to int64 extremes"],
    ["cast-09", "CAST '0x10' AS INTEGER is 0"],
    ["cmp-01", "INTEGER vs TEXT with column affinity"],
    ["cmp-02", "Bare literal '10' < 9 comparison"],
    ["sort-01", "NULL sorts first"],
    ["sort-02", "INTEGER/REAL interleave numerically"],
    ["sort-03", "TEXT after numbers"],
    ["sort-04", "BLOB after TEXT"],
    ["int-01", "int64 min round-trip"],
    ["int-02", "int64 max round-trip"],
    ["int-03", "9223372036854775807 + 1 arithmetic"],
    ["int-04", "Values beyond MAX_SAFE_INTEGER as bigint"],
    ["negzero-01", "Bind -0 canonicalized to +0", D, "README determinism"],
    ["negzero-02", "Arithmetic -0 canonicalized to +0", D, "README determinism"],
    ["negzero-03", "min(-0.0, 0.0) is +0", D, "README determinism"],
    ["blob-01", "BLOB comparison is memcmp"],
    ["blob-02", "BLOB differing lengths"],
    ["blob-03", "Empty blob"],
    ["text-01", "TEXT comparison BINARY codepoint/byte order"],
    ["nan-01", "0.0/0.0 is NULL in SQL"],
    ["nan-02", "9e999 Inf REAL"],
    ["nan-03", "1e308*10 overflow behavior"],
    ["nan-04", "JS bind of NaN rejected datatype_mismatch", D],
    ["nan-05", "JS bind of Infinity rejected datatype_mismatch", D],
  ]),
  section("EXP", "Operators & expression semantics", true, [
    ["arith-01", "Addition across types", undefined, undefined, ["tests/contract/matrices/m1-operators.test.ts"]],
    ["arith-02", "Subtraction across types"],
    ["arith-03", "Multiplication across types"],
    ["arith-04", "Integer division truncates toward zero"],
    ["arith-05", "Division by zero is NULL"],
    ["arith-06", "Modulo by zero is NULL"],
    ["arith-07", "Modulo with REAL"],
    ["arith-08", "Integer overflow in + - *"],
    ["concat-01", "|| with NULL"],
    ["concat-02", "|| formats REAL including 1.0"],
    ["concat-03", "|| with blobs"],
    ["concat-04", "concat() NULL handling vs ||"],
    ["concat-05", "concat_ws() NULL handling"],
    ["null-01", "Comparisons with NULL yield NULL"],
    ["is-01", "IS / IS NOT"],
    ["is-02", "IS DISTINCT FROM"],
    ["is-03", "IS NOT DISTINCT FROM"],
    ["between-01", "BETWEEN inclusive bounds"],
    ["between-02", "BETWEEN with NULL operands"],
    ["between-03", "BETWEEN with collation"],
    ["in-01", "IN value list"],
    ["in-02", "NOT IN empty subquery"],
    ["in-03", "1 NOT IN (2, NULL) is NULL"],
    ["in-04", "IN subquery"],
    ["in-05", "Row-value IN SELECT"],
    ["in-06", "IN with table name"],
    ["like-01", "LIKE ASCII case-insensitivity"],
    ["like-02", "LIKE % and _"],
    ["like-03", "LIKE ESCAPE clause"],
    ["like-04", "LIKE multi-char ESCAPE errors"],
    ["like-05", "LIKE non-ASCII case sensitivity"],
    ["like-06", "PRAGMA case_sensitive_like"],
    ["like-07", "LIKE on numbers/blobs/NULL"],
    ["glob-01", "GLOB is case-sensitive"],
    ["glob-02", "GLOB * and ?"],
    ["glob-03", "GLOB [a-z] classes"],
    ["glob-04", "GLOB [^] classes"],
    ["regexp-01", "REGEXP error parity"],
    ["match-01", "MATCH outside FTS error parity"],
    ["bit-01", "Bitwise AND OR NOT"],
    ["bit-02", "Shifts and counts >= 64"],
    ["bit-03", "Negative shift counts"],
    ["bit-04", "Bitwise NULL propagation"],
    ["bit-05", "Bitwise TEXT coerced to INTEGER"],
    ["unary-01", "Unary +"],
    ["unary-02", "Unary - on TEXT"],
    ["not-01", "NOT 'abc' is 1"],
    ["not-02", "NOT '1x' is 0"],
    ["truth-01", "WHERE '1' is true"],
    ["truth-02", "WHERE '1.5' is true"],
    ["truth-03", "WHERE 'abc' is false"],
    ["truth-04", "WHERE 0.5 is true"],
    ["truth-05", "WHERE NULL is false"],
    ["bool-01", "TRUE/FALSE literals"],
    ["bool-02", "Column named true shadows literal"],
    ["bool-03", "IS TRUE/FALSE including NULL"],
    ["case-01", "Simple CASE"],
    ["case-02", "Searched CASE"],
    ["case-03", "CASE NULL base"],
    ["case-04", "CASE without ELSE"],
    ["exists-01", "EXISTS / NOT EXISTS"],
    ["scalar-01", "Scalar subquery zero rows is NULL"],
    ["scalar-02", "Scalar subquery multiple rows takes first"],
    ["scalar-03", "Correlated scalar subquery"],
    ["iif-01", "iif()"],
    ["nullif-01", "nullif()"],
    ["coalesce-01", "coalesce/ifnull"],
    ["row-01", "Row-value equality"],
    ["row-02", "Row-value ordering"],
    ["row-03", "Row-value size mismatch error"],
  ]),
];

const TAIL: CatalogSection[] = [
    section("FUN", "Built-in scalar functions", true, [
      ["length-01", "length() TEXT codepoints"],
      ["length-02", "length() BLOB bytes"],
      ["length-03", "length() of numbers"],
      ["octet-01", "octet_length()"],
      ["substr-01", "substr negative start"],
      ["substr-02", "substr start 0"],
      ["substr-03", "substr negative length"],
      ["substr-04", "substr on blob"],
      ["substr-05", "substring() alias"],
      ["instr-01", "instr text and blob mixes"],
      ["replace-01", "replace empty pattern"],
      ["upper-01", "upper ASCII-only"],
      ["lower-01", "lower ASCII-only"],
      ["trim-01", "trim/ltrim/rtrim charset"],
      ["hex-01", "hex()"],
      ["unhex-01", "unhex ignore-chars"],
      ["unhex-02", "unhex invalid is NULL"],
      ["quote-01", "quote text blobs REAL NULL"],
      ["char-01", "char multiple codepoints"],
      ["unicode-01", "unicode()"],
      ["soundex-01", "soundex if present"],
      ["printf-01", "printf/format specifiers"],
      ["printf-02", "printf width precision flags"],
      ["printf-03", "printf NULL args"],
      ["abs-01", "abs()"],
      ["abs-02", "abs(int64 min) error parity"],
      ["round-01", "round 2-arg and .5"],
      ["round-02", "round negative precision"],
      ["sign-01", "sign()"],
      ["minmax-01", "scalar min/max ignore NULLs"],
      ["minmax-02", "scalar min/max 1-arg error"],
      ["random-01", "random() range"],
      ["randomblob-01", "randomblob N<=0 is 1 byte"],
      ["zeroblob-01", "zeroblob huge N error"],
      ["hint-01", "likelihood/likely/unlikely pass-through"],
      ["math-01", "trig and hyperbolic domain errors"],
      ["math-02", "ceil/floor/trunc types"],
      ["math-03", "log family and pow"],
      ["math-04", "mod sign behavior"],
      ["math-05", "pi degrees radians"],
      ["typeof-01", "typeof()"],
      ["version-01", "sqlite_version"],
      ["source-01", "sqlite_source_id"],
      ["lastrow-01", "last_insert_rowid() SQL function"],
      ["changes-01", "changes()/total_changes() SQL functions"],
      ["like-fn-01", "like() function form"],
      ["glob-fn-01", "glob() function form"],
      ["coalesce-01", "coalesce 1 arg errors"],
      ["null-01", "NULL argument behavior for scalars"],
      ["arity-01", "wrong-arity errors"],
    ]),
    section("DAT", "Date & time functions", true, [
      ["fn-01", "date()"],
      ["fn-02", "time()"],
      ["fn-03", "datetime()"],
      ["fn-04", "julianday()"],
      ["fn-05", "unixepoch()"],
      ["fn-06", "unixepoch subsec"],
      ["fn-07", "timediff()"],
      ["strftime-01", "strftime common specifiers"],
      ["strftime-02", "strftime remaining specifiers"],
      ["strftime-03", "strftime invalid specifier"],
      ["in-01", "YYYY-MM-DD input"],
      ["in-02", "datetime with T separator"],
      ["in-03", "fractional seconds input"],
      ["in-04", "now input"],
      ["in-05", "julian day number input"],
      ["in-06", "unixepoch auto modifier"],
      ["in-07", "malformed date is NULL"],
      ["in-08", "out-of-range date is NULL"],
      ["mod-01", "plus N days hours minutes"],
      ["mod-02", "plus N months years"],
      ["mod-03", "fractional seconds modifier"],
      ["mod-04", "HH:MM offset modifier"],
      ["mod-05", "start of day/month/year"],
      ["mod-06", "weekday N"],
      ["mod-07", "unixepoch julianday auto modifiers"],
      ["mod-08", "localtime/utc modifiers", D, "fixed default clock"],
      ["mod-09", "subsec floor ceiling"],
      ["mod-10", "invalid modifier is NULL"],
      ["cal-01", "month-end +1 month"],
      ["cal-02", "leap year 2000-02-29"],
      ["cal-03", "1900 is not leap"],
      ["cal-04", "year 0 and 9999 bounds"],
      ["now-01", "default now is 2000-01-01", D, "README"],
      ["now-02", "CURRENT_TIMESTAMP/DATE/TIME", D, "README"],
      ["now-03", "column DEFAULT CURRENT_TIMESTAMP", D, "README"],
      ["now-04", "now system tracks wall clock", D, "README"],
      ["now-05", "now fn called per statement", D, "README"],
      ["now-06", "open freezes clock", D, "README"],
    ]),
    section("JSN", "JSON", true, [
      ["json-01", "json() minify/validate"],
      ["valid-01", "json_valid"],
      ["valid-02", "json_valid flags"],
      ["errpos-01", "json_error_position"],
      ["arr-01", "json_array"],
      ["obj-01", "json_object"],
      ["obj-02", "json_object odd arg count error"],
      ["quote-01", "json_quote"],
      ["extract-01", "json_extract single path"],
      ["extract-02", "json_extract multi-path"],
      ["arrow-01", "-> JSON result"],
      ["arrow-02", "->> SQL value"],
      ["arrow-03", "integer path shorthand"],
      ["path-01", "$ and $.a.b"],
      ["path-02", "$[0] and $[#-1]"],
      ["path-03", "quoted path keys"],
      ["path-04", "invalid path error"],
      ["set-01", "json_set"],
      ["insert-01", "json_insert"],
      ["replace-01", "json_replace"],
      ["remove-01", "json_remove multi-path order"],
      ["patch-01", "json_patch RFC 7396"],
      ["type-01", "json_type with path"],
      ["len-01", "json_array_length"],
      ["garr-01", "json_group_array"],
      ["gobj-01", "json_group_object"],
      ["each-01", "json_each columns"],
      ["each-02", "json_each correlated"],
      ["tree-01", "json_tree columns"],
      ["sub-01", "JSON subtype into json_array"],
      ["sub-02", "TEXT that looks like JSON vs subtype"],
      ["sub-03", "API unwraps JSON subtype to string", D, "README"],
      ["jsonb-01", "jsonb_* variants"],
    ]),
    section("AGG", "Aggregate functions", true, [
      ["count-01", "count(*) vs count(x)"],
      ["count-02", "count DISTINCT"],
      ["sum-01", "sum empty is NULL"],
      ["sum-02", "total empty is 0.0"],
      ["sum-03", "sum integer overflow errors"],
      ["sum-04", "total overflow is REAL"],
      ["avg-01", "avg always REAL"],
      ["minmax-01", "min/max cross-type"],
      ["minmax-02", "min/max all-NULL"],
      ["gconcat-01", "group_concat default separator"],
      ["gconcat-02", "group_concat custom separator"],
      ["gconcat-03", "string_agg"],
      ["gconcat-04", "group_concat DISTINCT"],
      ["gconcat-05", "group_concat ORDER BY"],
      ["filter-01", "FILTER WHERE on aggregates"],
      ["distinct-01", "DISTINCT inside aggregates"],
      ["distinct-02", "multi-arg DISTINCT error"],
      ["empty-01", "aggregates no GROUP BY on empty table"],
      ["having-01", "HAVING without GROUP BY"],
      ["bare-01", "bare column with max()"],
      ["nested-01", "nested aggregates error"],
      ["where-01", "aggregates in WHERE error"],
    ]),
    section("WIN", "Window functions", true, [
      ["rank-01", "row_number"],
      ["rank-02", "rank"],
      ["rank-03", "dense_rank"],
      ["rank-04", "percent_rank"],
      ["rank-05", "cume_dist"],
      ["ntile-01", "ntile remainder"],
      ["ntile-02", "ntile N<=0 error"],
      ["lag-01", "lag/lead offsets"],
      ["lag-02", "lag/lead default value"],
      ["nth-01", "first_value last_value nth_value"],
      ["agg-01", "aggregates as windows"],
      ["filter-01", "window FILTER"],
      ["part-01", "PARTITION BY multi-key"],
      ["order-01", "window ORDER BY collation"],
      ["order-02", "window NULLS FIRST/LAST"],
      ["frame-01", "ROWS frames"],
      ["frame-02", "RANGE frames"],
      ["frame-03", "GROUPS frames"],
      ["frame-04", "RANGE numeric offsets"],
      ["excl-01", "EXCLUDE NO OTHERS"],
      ["excl-02", "EXCLUDE CURRENT ROW"],
      ["excl-03", "EXCLUDE GROUP"],
      ["excl-04", "EXCLUDE TIES"],
      ["named-01", "WINDOW clause named windows"],
      ["named-02", "window inheritance chaining"],
      ["sub-01", "windows in subqueries"],
      ["empty-01", "window over empty partition"],
      ["peer-01", "RANGE peer/ties semantics"],
    ]),
    section("SEL", "SELECT core semantics", true, [
      ["proj-01", "star projection"],
      ["proj-02", "t.* projection"],
      ["alias-01", "alias in ORDER BY"],
      ["alias-02", "alias in GROUP BY"],
      ["alias-03", "alias in WHERE errors"],
      ["dup-01", "duplicate output names row-object collapse", D, "README values vs rows"],
      ["distinct-01", "DISTINCT NULL dedup"],
      ["distinct-02", "DISTINCT collation"],
      ["group-01", "GROUP BY expression"],
      ["group-02", "GROUP BY ordinal"],
      ["group-03", "GROUP BY alias"],
      ["group-04", "GROUP BY NULLs together"],
      ["group-05", "GROUP BY ordinal out of range"],
      ["having-01", "HAVING aggregates and bare columns"],
      ["order-01", "ORDER BY ordinal alias expression"],
      ["order-02", "ORDER BY COLLATE ASC DESC"],
      ["order-03", "ORDER BY NULLS FIRST/LAST"],
      ["limit-01", "negative LIMIT is unlimited"],
      ["limit-02", "LIMIT x,y swapped form"],
      ["limit-03", "expressions in LIMIT"],
      ["union-01", "UNION vs UNION ALL"],
      ["union-02", "INTERSECT EXCEPT"],
      ["union-03", "compound column-count mismatch"],
      ["union-04", "ORDER BY LIMIT apply to whole compound"],
      ["values-01", "VALUES statement column1 naming"],
      ["sub-01", "subquery in FROM"],
      ["sub-02", "correlated subquery visibility"],
    ]),
    section("JOI", "Joins", true, [
      ["inner-01", "INNER JOIN ON"],
      ["inner-02", "INNER JOIN USING"],
      ["comma-01", "implicit comma join"],
      ["cross-01", "CROSS JOIN"],
      ["left-01", "LEFT JOIN NULL padding"],
      ["left-02", "ON vs WHERE placement"],
      ["left-03", "LEFT JOIN subquery/VALUES"],
      ["right-01", "RIGHT JOIN"],
      ["full-01", "FULL OUTER JOIN"],
      ["natural-01", "NATURAL join matching"],
      ["natural-02", "NATURAL with no common columns"],
      ["natural-03", "NATURAL LEFT"],
      ["using-01", "USING column dedup in star"],
      ["using-02", "qualified names after USING"],
      ["paren-01", "join-tree parenthesization"],
      ["self-01", "self-join aliases"],
      ["mix-01", "three-table mixed join types"],
      ["rowid-01", "join on rowid"],
      ["later-01", "ON referencing later table errors"],
    ]),
    section("CTE", "Common table expressions", true, [
      ["basic-01", "WITH basic"],
      ["multi-01", "multiple CTEs"],
      ["cols-01", "CTE column-name list"],
      ["shadow-01", "CTE shadows real table"],
      ["multi-ref-01", "CTE referenced multiple times"],
      ["chain-01", "CTE references earlier CTE"],
      ["fwd-01", "forward CTE reference errors"],
      ["rec-01", "WITH RECURSIVE UNION dedup"],
      ["rec-02", "WITH RECURSIVE UNION ALL"],
      ["rec-03", "recursive term shape errors"],
      ["rec-04", "LIMIT inside recursion"],
      ["rec-05", "ORDER BY steers recursive queue"],
      ["rec-06", "counter to N fixture"],
      ["mat-01", "MATERIALIZED vs NOT MATERIALIZED", D, "both materialized"],
      ["view-01", "CTE inside views"],
      ["dml-01", "WITH INSERT UPDATE DELETE"],
    ]),
    section("DDL", "Schema definition", true, [
      ["ct-01", "CREATE TABLE IF NOT EXISTS"],
      ["ct-02", "quoted and keyword table names"],
      ["ct-03", "column NOT NULL DEFAULT UNIQUE PK CHECK COLLATE REFERENCES"],
      ["ct-04", "table-level composite PK UNIQUE CHECK FK"],
      ["ct-05", "duplicate name error"],
      ["ipk-01", "INTEGER PRIMARY KEY is rowid alias"],
      ["ipk-02", "INTEGER PRIMARY KEY DESC is not alias"],
      ["ipk-03", "INT PRIMARY KEY is not rowid alias"],
      ["auto-01", "AUTOINCREMENT sqlite_sequence"],
      ["auto-02", "AUTOINCREMENT after deletes"],
      ["auto-03", "AUTOINCREMENT max-rowid SQLITE_FULL"],
      ["wor-01", "WITHOUT ROWID requires PK"],
      ["wor-02", "WITHOUT ROWID no rowid access"],
      ["strict-01", "STRICT allowed types"],
      ["strict-02", "STRICT ANY and WITHOUT ROWID"],
      ["gen-01", "GENERATED ALWAYS VIRTUAL STORED"],
      ["gen-02", "cannot INSERT into generated columns"],
      ["ctas-01", "CREATE TABLE AS SELECT"],
      ["alter-01", "ALTER RENAME TO"],
      ["alter-02", "ALTER RENAME COLUMN"],
      ["alter-03", "ALTER ADD COLUMN restrictions"],
      ["alter-04", "ALTER DROP COLUMN restrictions"],
      ["idx-01", "CREATE UNIQUE INDEX"],
      ["idx-02", "expression and partial indexes"],
      ["idx-03", "indexes never change query results"],
      ["view-01", "CREATE VIEW column list"],
      ["view-02", "DML on plain view errors"],
      ["drop-01", "DROP IF EXISTS and cascade indexes/triggers"],
      ["master-01", "sqlite_schema / sqlite_master shape"],
      ["master-02", "direct writes to sqlite_master rejected"],
      ["temp-01", "TEMP objects name resolution"],
      ["case-01", "case-insensitive schema names"],
    ]),
    section("DML", "Data modification", true, [
      ["ins-01", "INSERT multi-row VALUES"],
      ["ins-02", "INSERT DEFAULT VALUES"],
      ["ins-03", "INSERT SELECT including same table"],
      ["ins-04", "column/value count mismatch"],
      ["ins-05", "explicit rowid insert"],
      ["ins-06", "NULL rowid auto-assign"],
      ["ins-07", "negative rowids"],
      ["ins-08", "rowid reuse after delete"],
      ["or-01", "INSERT OR REPLACE"],
      ["or-02", "INSERT OR IGNORE"],
      ["or-03", "INSERT OR ABORT"],
      ["or-04", "INSERT OR FAIL partial progress"],
      ["or-05", "INSERT OR ROLLBACK kills txn"],
      ["up-01", "UPSERT DO NOTHING"],
      ["up-02", "UPSERT DO UPDATE excluded"],
      ["up-03", "UPSERT conflict target WHERE"],
      ["up-04", "UPSERT target-less"],
      ["up-05", "multiple ON CONFLICT clauses"],
      ["up-06", "UPSERT RETURNING"],
      ["upd-01", "UPDATE expressions"],
      ["upd-02", "UPDATE FROM"],
      ["upd-03", "UPDATE rowid and PK"],
      ["del-01", "DELETE WHERE"],
      ["del-02", "DELETE FROM t changes count"],
      ["ret-01", "RETURNING INSERT UPDATE DELETE"],
      ["ret-02", "RETURNING via run discards rows", D, "API"],
      ["chg-01", "changes lastInsertRowid after DML"],
      ["chg-02", "exec last statement wins counters"],
      ["chg-03", "trigger-driven changes not in db.changes"],
      ["chg-04", "total_changes monotonic"],
    ]),
    section("CON", "Constraints & enforcement", true, [
      ["nn-01", "NOT NULL with conflict clauses"],
      ["uq-01", "UNIQUE allows multiple NULLs"],
      ["uq-02", "UNIQUE composite error message"],
      ["pk-01", "PRIMARY KEY NULL on rowid table auto-assigns"],
      ["pk-02", "PRIMARY KEY NULL on WITHOUT ROWID"],
      ["ck-01", "CHECK NULL result passes"],
      ["ck-02", "CHECK on INSERT and UPDATE"],
      ["fk-01", "foreign_keys default OFF"],
      ["fk-02", "FK ON with parent UNIQUE/PK"],
      ["fk-03", "FK CASCADE SET NULL SET DEFAULT"],
      ["fk-04", "FK RESTRICT NO ACTION"],
      ["fk-05", "DEFERRABLE INITIALLY DEFERRED"],
      ["fk-06", "self-referential FK"],
      ["fk-07", "composite FK"],
      ["fk-08", "FK INSERT OR REPLACE"],
      ["fk-09", "foreign_key_check and foreign_key_list"],
      ["err-01", "constraint_unique sqliteCode"],
      ["err-02", "constraint_notnull sqliteCode"],
      ["err-03", "constraint_check sqliteCode"],
      ["err-04", "constraint_foreignkey sqliteCode"],
      ["err-05", "constraint_primarykey sqliteCode"],
    ]),
    section("TRG", "Triggers", true, [
      ["bi-01", "BEFORE/AFTER INSERT UPDATE DELETE"],
      ["of-01", "UPDATE OF col"],
      ["when-01", "WHEN clause"],
      ["old-01", "OLD/NEW visibility"],
      ["ord-01", "trigger firing order is creation order"],
      ["rec-01", "PRAGMA recursive_triggers"],
      ["raise-01", "RAISE ABORT FAIL ROLLBACK"],
      ["raise-02", "RAISE IGNORE"],
      ["instead-01", "INSTEAD OF on views"],
      ["fk-01", "triggers and FK cascade ordering"],
      ["chg-01", "triggers do not affect db.changes"],
      ["drop-01", "DROP TABLE drops triggers"],
      ["snap-01", "triggers not encoded in snapshots", D, "README"],
    ]),
    section("TXN", "Transactions & savepoints", true, [
      ["begin-01", "BEGIN DEFERRED IMMEDIATE EXCLUSIVE"],
      ["commit-01", "COMMIT and END"],
      ["rb-01", "ROLLBACK"],
      ["nest-01", "nested BEGIN errors"],
      ["commit-02", "COMMIT with no txn errors"],
      ["sp-01", "SAVEPOINT name scoping"],
      ["sp-02", "RELEASE releases through"],
      ["sp-03", "ROLLBACK TO keeps savepoint"],
      ["sp-04", "savepoint outside txn"],
      ["atom-01", "failed multi-row INSERT ABORT atomicity"],
      ["api-01", "db.transaction commit on return"],
      ["api-02", "db.transaction rollback on throw"],
      ["api-03", "nested transaction uses savepoints"],
      ["api-04", "close inside transaction is misuse"],
      ["rb-02", "rollback restores schema"],
      ["rb-03", "rollback restores PRNG", D, "README"],
      ["close-01", "close mid-transaction rolls back"],
    ]),
    section("PRG", "PRAGMA surface", true, [
      ["ti-01", "table_info / table_xinfo"],
      ["idx-01", "index_list index_info index_xinfo"],
      ["db-01", "database_list"],
      ["fk-01", "foreign_key_list"],
      ["fn-01", "function_list", D, "sqlite-mem own set"],
      ["col-01", "collation_list"],
      ["tl-01", "table_list"],
      ["tvf-01", "pragma_* TVFs correlated"],
      ["beh-01", "foreign_keys pragma"],
      ["beh-02", "defer_foreign_keys", D, "setter currently no-op; getter returns 0"],
      ["beh-03", "recursive_triggers", D, "setter currently no-op; getter returns 0"],
      ["beh-04", "case_sensitive_like"],
      ["beh-05", "user_version get/set", D, "snapshot exclusion"],
      ["beh-06", "schema_version bumps on DDL"],
      ["beh-07", "application_id", D, "setter currently no-op; getter returns 0"],
      ["health-01", "integrity_check quick_check ok"],
      ["health-02", "foreign_key_check rows"],
      ["stor-01", "journal_mode memory default"],
      ["stor-02", "encoding UTF-8"],
      ["unk-01", "unknown pragma empty success"],
      ["schema-01", "schema-prefixed pragma"],
      ["comp-01", "compile_options sqlite-mem set", D],
    ]),
    section("COL", "Collations", true, [
      ["bin-01", "BINARY collation"],
      ["nc-01", "NOCASE ASCII-only"],
      ["rt-01", "RTRIM trailing spaces"],
      ["eq-01", "collation on ="],
      ["ord-01", "collation on ORDER BY"],
      ["grp-01", "collation on GROUP BY"],
      ["dist-01", "collation on DISTINCT"],
      ["in-01", "collation on IN BETWEEN"],
      ["res-01", "COLLATE operator beats column"],
      ["res-02", "binary operator uses left collation"],
      ["idx-01", "NOCASE unique index"],
      ["unk-01", "unknown collation error"],
    ]),
    section("FTS", "Full-text search & virtual tables", true, [
      ["f5-01", "FTS5 CREATE VIRTUAL TABLE"],
      ["f5-02", "FTS5 INSERT UPDATE DELETE"],
      ["f5-03", "MATCH AND OR NOT"],
      ["f5-04", "MATCH NEAR phrases prefix"],
      ["f5-05", "column filters"],
      ["f5-06", "rank and bm25"],
      ["f5-07", "highlight snippet"],
      ["f5-08", "fts5 special commands"],
      ["f34-01", "FTS3/4 MATCH"],
      ["f34-02", "matchinfo offsets"],
      ["chg-01", "shadow-table change counters", D, "README"],
      ["snap-01", "virtual tables not in snapshots", D, "README"],
      ["series-01", "generate_series", D, "sqlite-mem extension; not in bun:sqlite default"],
    ]),
    section("ATT", "ATTACH / DETACH / schemas", true, [
      ["att-01", "ATTACH anything is empty in-memory schema", D, "filename ignored for data"],
      ["att-02", "duplicate schema name error"],
      ["det-01", "DETACH unknown name error"],
      ["det-02", "cannot detach main/temp"],
      ["qual-01", "qualified schema.table names"],
      ["res-01", "temp then main then attached resolution"],
      ["amb-01", "ambiguity errors"],
      ["cross-01", "cross-schema queries and joins"],
      ["list-01", "database_list reflects attachments"],
      ["snap-01", "snapshot excludes attached schemas", D, "README"],
    ]),
    section("API", "JavaScript surface contracts", true, [
      ["exec-01", "exec multi-statement void"],
      ["exec-02", "exec rejects binds"],
      ["exec-03", "exec partial failure persists prior"],
      ["query-01", "query single-statement"],
      ["query-02", "query positional binds"],
      ["prep-01", "prepare-time syntax errors"],
      ["prep-02", "prepared statement reuse"],
      ["prep-03", "schema invalidation re-prepare"],
      ["run-01", "run all get result shapes"],
      ["run-02", "get zero rows undefined"],
      ["run-03", "result empty values for zero rows"],
      ["run-04", "run on SELECT discards rows"],
      ["run-05", "all on INSERT RETURNING"],
      ["bind-01", "accepted bind types"],
      ["bind-02", "rejected bind types"],
      ["bind-03", "blob binds are copied"],
      ["named-01", "named params first-occurrence order"],
      ["named-02", "@x $x :x are distinct"],
      ["named-03", "?NNN indexing"],
      ["ret-01", "bigint threshold"],
      ["ret-02", "Uint8Array freshness"],
      ["ret-03", "duplicate column last-write-wins"],
      ["close-01", "close idempotent and misuse after"],
      ["close-02", "Symbol.dispose"],
      ["txn-01", "query inside transaction(fn)"],
      ["sync-01", "methods return non-Promises"],
    ]),
    section("SNP", "Snapshot / restore", true, [
      ["rt-01", "round-trip schema and rows"],
      ["rt-02", "round-trip blobs unicode NUL"],
      ["rt-03", "round-trip counters sqlite_sequence"],
      ["rt-04", "round-trip PRNG and clock"],
      ["byte-01", "byte-identical equivalent DBs"],
      ["hdr-01", "SQLM magic and version"],
      ["hdr-02", "corrupt magic error"],
      ["hdr-03", "truncated blob error"],
      ["hdr-04", "future version snapshot_version"],
      ["txn-01", "snapshot during txn errors"],
      ["now-01", "open with system clock stays live", D],
      ["now-02", "open overwrites Date fn with snapshot clock", D],
      ["rng-01", "open with random os does not rewind", D],
      ["omit-01", "triggers not encoded", D],
      ["omit-02", "ATTACH not encoded", D],
      ["omit-03", "virtual tables not encoded", D],
      ["omit-04", "user_version not encoded", D],
      ["open-01", "Snapshot.open CoW fork"],
      ["open-02", "encode does not mutate; decode reuses buffer"],
    ]),
    section("DET", "Determinism invariants", true, [
      ["seed-01", "same seed identical random streams", D],
      ["seed-02", "different seeds diverge", D],
      ["os-01", "random os full-range int64", D],
      ["eval-01", "PRNG consumption in CASE", D],
      ["rb-01", "PRNG rolls back with ROLLBACK", D],
      ["rb-02", "PRNG does not roll back on COMMIT", D],
      ["scan-01", "full-table scans in rowid order"],
      ["negzero-01", "-0 to +0 at bind affinity arithmetic snapshot", D],
    ]),
    section("ERR", "Error parity", true, [
      ["cat-01", "syntax category and sqliteCode"],
      ["cat-02", "no such table"],
      ["cat-03", "no such column"],
      ["cat-04", "UNIQUE constraint failed message"],
      ["cat-05", "datatype mismatch"],
      ["cat-06", "near syntax error"],
      ["time-01", "syntax at prepare"],
      ["time-02", "no such table at prepare"],
      ["time-03", "constraint at run"],
      ["state-01", "errors leave DB usable"],
      ["inst-01", "instanceof SqliteError"],
    ]),
    section("UNI", "Unicode, encoding, weird text", true, [
      ["utf-01", "multi-byte UTF-8 round-trip"],
      ["len-01", "length counts codepoints"],
      ["astral-01", "astral-plane in length substr instr"],
      ["surr-01", "lone surrogates from JS binds", D],
      ["nul-01", "embedded NUL in TEXT"],
      ["fold-01", "upper/lower/NOCASE/LIKE ASCII only"],
      ["char-01", "char/unicode round trip"],
      ["hex-01", "hex of multi-byte via CAST blob"],
    ]),
    section("LIM", "Limits & pathological inputs", true, [
      ["depth-01", "expression depth near limit"],
      ["cmpd-01", "compound SELECT term count"],
      ["cols-01", "columns per table"],
      ["vals-01", "terms in VALUES"],
      ["in-01", "large IN list"],
      ["ident-01", "identifier length"],
      ["like-01", "LIKE pattern length"],
      ["zero-01", "empty table empty string PK"],
      ["zero-02", "SELECT with no FROM"],
      ["fuzz-01", "past fuzz failures as named contracts"],
    ]),
    section("FZZ", "Differential fuzz & property harness", true, [
      ["diff-01", "grammar-based differential fuzz", F],
      ["join-01", "join-weighted fuzz", F],
      ["aff-01", "affinity coercion fuzz", F],
      ["win-01", "window frame fuzz", F],
      ["up-01", "UPSERT fuzz", F],
      ["date-01", "date modifier fuzz", F],
      ["trig-01", "BEFORE/AFTER trigger + RAISE fuzz", F],
      ["genc-01", "STORED/VIRTUAL generated column fuzz", F],
      ["notin-01", "NOT IN / IN NULL + scalar cardinality fuzz", F],
      ["cnt-01", "changes/total_changes/last_insert_rowid fuzz", F],
      ["fkedge-01", "FK SET NULL/DEFAULT/MATCH edge fuzz", F],
      ["tlp-01", "ternary logic partitioning metamorphic", F],
      ["norec-01", "NoREC metamorphic rewrite", F],
      ["robust-01", "SqliteError-only / timeout / SQLM bit-flip", F],
      ["slt-01", "sqllogictest vendor corpus differential", F],
      ["dst-01", "mixed dump-after-each DST engine", F],
      ["prop-01", "snapshot restore idempotence", P],
      ["prop-02", "insert then delete snapshot bytes", P],
      ["prop-03", "index-added vs index-free equivalence", P],
      ["prop-04", "transaction throw never ran", P],
      ["prop-05", "exec a;b equivalent split exec", P],
      ["seed-01", "default seed 0x5a17e0e1", F],
      ["replay-01", "SQLITE_MEM_FUZZ_SEED PATH replay", F],
      ["gate-01", "fail-closed catalog mapping", P],
    ]),
    section("ECO", "Ecosystem integration smoke", true, [
      ["kysely-01", "Kysely introspection pragmas", E],
      ["drizzle-01", "Drizzle-style CRUD", E],
      ["knex-01", "Knex-style queries", E],
      ["prisma-01", "Prisma-style introspection", E],
      ["mig-01", "migration-runner transactional DDL", E],
      ["b3-01", "absent better-sqlite3 extras error", E],
      ["readme-01", "README pitfalls as tests", E],
      ["node-01", "Node canonical script smoke", E],
    ]),
];

export const SCENARIO_CATALOG: CatalogSection[] = [...HEAD, ...TAIL];

export function allScenarios(): Scenario[] {
  return SCENARIO_CATALOG.flatMap((section) => section.scenarios);
}

export function scenarioById(): Map<string, Scenario> {
  return new Map(allScenarios().map((scenario) => [scenario.id, scenario]));
}

export function knownScenarioIds(): Set<string> {
  return new Set(allScenarios().map((scenario) => scenario.id));
}
